- hosts: all
  remote_user: root
  tasks:
    - name: httpd install
      yum:
        name: httpd
        state: present
      become: True
    - name: httpd run  
      service:
        name: httpd
        state: started
        enabled: True
      become: True 
              
