- hosts: all
  remote_user: root
  tasks:
    - yum:
        name: httpd
        state: present
      become: True
    - service:
        name: httpd
        state: started
        enabled: True
      become: True 
              
